[package]
name              = "miden-standards-faucets-policies-transfer-blocklist-manager"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::faucets::policies::transfer::blocklist::manager"
path      = "manager.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
