// This file is @generated by `make update-note-costs`. Do not edit by hand.
// Values are maxima across the benchmarked paths; see `miden_standards::note::costs` for the
// caveats on what they do and do not cover.

/// Cycles of consuming a P2ID note: 1 asset 18648, 16 assets 56946 (maximum).
pub const P2ID_CONSUMPTION_CYCLES: u32 = 56946;

/// Cycles of consuming a P2IDE note: claim 18772, claim with 16 assets 57070 (maximum), reclaim
/// 18927.
pub const P2IDE_CONSUMPTION_CYCLES: u32 = 57070;

/// Cycles of consuming a SWAP note: public payback 22697 (maximum), private payback 22178.
pub const SWAP_CONSUMPTION_CYCLES: u32 = 22697;

/// Cycles of consuming a PSWAP note: full fill 25293, partial fill 29310 (maximum).
pub const PSWAP_CONSUMPTION_CYCLES: u32 = 29310;

/// Cycles of consuming a MINT note: fungible faucet 33475, non-fungible faucet 36815 (maximum).
pub const MINT_CONSUMPTION_CYCLES: u32 = 36815;

/// Cycles of consuming a BURN note (single benchmarked path).
pub const BURN_CONSUMPTION_CYCLES: u32 = 29452;

/// Cycles of consuming a CONSTANT_FEE_POLICY_CONFIG note (single benchmarked path).
pub const CONSTANT_FEE_POLICY_CONFIG_CONSUMPTION_CYCLES: u32 = 20058;

/// Cycles of consuming a FAUCET_POLICY_CONFIG note (single benchmarked path).
pub const FAUCET_POLICY_CONFIG_CONSUMPTION_CYCLES: u32 = 27618;

/// Cycles of consuming a FAUCET_METADATA_CONFIG note (single benchmarked path).
pub const FAUCET_METADATA_CONFIG_CONSUMPTION_CYCLES: u32 = 27597;

/// Cycles of consuming a MIN_BURN_AMOUNT_CONFIG note (single benchmarked path).
pub const MIN_BURN_AMOUNT_CONFIG_CONSUMPTION_CYCLES: u32 = 25951;

/// Cycles of consuming an ALLOWLIST_CONFIG note (single benchmarked path).
pub const ALLOWLIST_CONFIG_CONSUMPTION_CYCLES: u32 = 26701;

/// Cycles of consuming a BLOCKLIST_CONFIG note (single benchmarked path).
pub const BLOCKLIST_CONFIG_CONSUMPTION_CYCLES: u32 = 26701;

/// Cycles of consuming a PAUSE_CONFIG note (single benchmarked path).
pub const PAUSE_CONFIG_CONSUMPTION_CYCLES: u32 = 18651;

/// Cycles of consuming an OWNER_CONFIG note (single benchmarked path).
pub const OWNER_CONFIG_CONSUMPTION_CYCLES: u32 = 18245;

/// Cycles of consuming an RBAC_CONFIG note (single benchmarked path).
pub const RBAC_CONFIG_CONSUMPTION_CYCLES: u32 = 22106;

/// Cycles of consuming a NETWORK_ACCOUNT_CONFIG note (single benchmarked path).
pub const NETWORK_ACCOUNT_CONFIG_CONSUMPTION_CYCLES: u32 = 19145;

/// Cycles of consuming a FEE_SPONSORSHIP note (single benchmarked path).
pub const FEE_SPONSORSHIP_CONSUMPTION_CYCLES: u32 = 21472;
