[package]
name              = "miden-standards-faucets-policies-policy-manager"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::faucets::policies::policy_manager"
path      = "policy_manager.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
