[package]
name              = "miden-standards-access-warden"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::access::warden"
path      = "warden.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
