[package]
name              = "miden-agglayer-bridge"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "agglayer::components::bridge"
path      = "bridge.masm"

[dependencies]
miden-agglayer.workspace  = true
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true

[package.metadata.account-component]
description = "AggLayer bridge"
name        = "agglayer::bridge"
version     = "1.0.0"
