[package]
name              = "miden-agglayer-config_agg_bridge"
version.workspace = true

[lib]
namespace = "agglayer::note_scripts::config_agg_bridge"
path      = "config_agg_bridge.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
miden-agglayer.workspace  = true
