[package]
name    = "miden-standards-faucets-policies-transfer-allowlist-owner-controlled"
version = "0.16.0"

[lib]
kind      = "account-component"
namespace = "miden::standards::components::faucets::policies::transfer::allowlist::owner_controlled"
path      = "owner_controlled.masm"

[dependencies]
miden-core      = { linkage = "dynamic", version = "0.23.4" }
miden-protocol  = { linkage = "dynamic", version = "0.16.0" }
miden-standards = { linkage = "static", version = "0.16.0" }
