[package]
name              = "expiration-tx-script"
version.workspace = true

[[bin]]
name = "expiration"
path = "expiration.masm"

[dependencies]
miden-core.workspace     = true
miden-protocol.workspace = true
