[package]
name              = "miden-standards-fees-policies-basic-constant-fee"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::fees::policies::basic_constant_fee"
path      = "basic_constant_fee.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
