[package]
name              = "miden-standards-utils-upgrade-manager"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::utils::upgrade::manager"
path      = "upgrade_manager.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
