[package]
name              = "tx-kernel"
version.workspace = true

[lib]
kind = "kernel"
path = "lib/api.masm"

[[bin]]
name = "main"
path = "main.masm"

[[bin]]
name = "tx-script-main"
path = "tx_script_main.masm"

[dependencies]
miden-utils.workspace = true
