[package]
authors.workspace      = true
categories             = ["development-tools::build-utils"]
description            = "Build-time helpers for assembling Miden MASM packages"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["build", "masm", "miden"]
license.workspace      = true
name                   = "miden-build-utils"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lib]
doctest = false
test    = false

[dependencies]
fs-err             = { workspace = true }
miden-assembly     = { features = ["std"], workspace = true }
miden-mast-package = { features = ["std"], workspace = true }
regex              = { workspace = true }
walkdir            = { workspace = true }
