[package]
name              = "miden-standards-access-scheduler"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::access::scheduler"
path      = "scheduler.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
