[package]
name    = "miden-standards-auth-network-account"
version = "0.16.0"

[lib]
kind      = "account-component"
namespace = "miden::standards::components::auth::network_account"
path      = "network_account.masm"

[dependencies]
miden-core      = { linkage = "dynamic", version = "0.23.4" }
miden-protocol  = { linkage = "dynamic", version = "0.16.0" }
miden-standards = { linkage = "static", version = "0.16.0" }
