// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 53] = [
    // account_get_initial_commitment
    word!("0x1ce31843eddd4125327fd9dcea977152f1146cd3fee05ffa6ed3b3d297d39333"),
    // account_compute_commitment
    word!("0x9b42f6f4d079c2012327f60da88a20a254c0ebc8bf1c534a85e03440be9de202"),
    // account_get_id
    word!("0xd76288f2e94b9e6a8f7eeee45c4ee0a23997d78496f6132e3f55681efea809c4"),
    // account_get_nonce
    word!("0x4a1f11db21ddb1f0ebf7c9fd244f896a95e99bb136008185da3e7d6aa85827a3"),
    // account_incr_nonce
    word!("0xd1316d21f95e20385283ac72914585a4a3281ff69935540d130fd1ace25ec9ae"),
    // account_get_code_commitment
    word!("0x8c044d53df35c71425c806b8997c6541e0aac70d7880657e9354b9854626ce3e"),
    // account_get_initial_storage_commitment
    word!("0x91377c2852feb7a2798e54d7dbaa2d97000270ec4c0d0888b26d720a25ae0e84"),
    // account_compute_storage_commitment
    word!("0x3a23d1218e58884afe87df989f56f923fe5cec6875587a7d3190b1d6a530d3fd"),
    // account_get_item
    word!("0x45ba71f27a225c85a6665621c05de15694480b2b93dec9e5e7d04e88837d862b"),
    // account_get_initial_item
    word!("0x2e05ba6d17df29bff36cf82a606d6f99cea79d93b13304f3a56593d26640a499"),
    // account_set_item
    word!("0x3ee533729555c1cde27172b1e3cdce0699236a496da8a845ca5e42688dd44f94"),
    // account_get_map_item
    word!("0x2159407657f4a3e078c02d00863db2821bdb80e6fa6bd0476759b723253786c5"),
    // account_get_initial_map_item
    word!("0x966b6ce9748bb5e4cc4166ed8c2ad716f504bdb00d914ac45d27fc4a11e26b10"),
    // account_set_map_item
    word!("0x49b9654ab872ebcf6cc3ffad8c1d70f53833b083df6d0b400acf45eacf91163a"),
    // account_get_initial_vault_root
    word!("0x46297d9ac95afd60c7ef1a065e024ad49aa4c019f6b3924191905449b244d4ec"),
    // account_get_vault_root
    word!("0x42a2bfb8eac4fce9bbf75ea15215b00729faeeaf7fff784692948d3f618a9bb7"),
    // account_add_asset
    word!("0xe2a410db129b2aabb18a72325cfc340ee0209f6dccd0d9ec030f427881934c78"),
    // account_remove_asset
    word!("0x5a91ab4a311011096a34bd5cd901d431cea63db5f05392c24fc902739572a14b"),
    // account_get_balance
    word!("0x6a5eb788fd2beec7555874f978a4dd2f2c4f5d8088cd33e148c61450e4510fe1"),
    // account_get_initial_balance
    word!("0x2e0decbc35a10c15ba72c14ed3e32dc9d4a3866f66114c073b3fc7b127362b74"),
    // account_has_non_fungible_asset
    word!("0xffe57961158c8e5f8a3aaa773943ee208fac7ed4786a7c8b6fed04ba54f39111"),
    // account_compute_delta_commitment
    word!("0x584a7c1302afc39069fab6fb387f2e3af1d8038d74cffd1cd70e860c1d422bf1"),
    // account_get_num_procedures
    word!("0x53b5ec38b7841948762c258010e6e07ad93963bcaac2d83813f8edb6710dc720"),
    // account_get_procedure_root
    word!("0xa45796077477599813ea54d88a83dfca3e64b1c112117970d63a1c24f7cfef5a"),
    // account_was_procedure_called
    word!("0xd9e08c27f3f1e7d01d257cbb4583ecf14f5e362d9c19e39ada8bc19dcc820d45"),
    // account_has_procedure
    word!("0xb0b63fdd01af0bcb4aacb2412e934cdc7691308647152d416c7ae4fc909da076"),
    // faucet_mint_asset
    word!("0xbc5e98fee461490c6fb13f9d81f830625170e386d4306a03c588a928f306a827"),
    // faucet_burn_asset
    word!("0x2b774759f18c1d221b0e9ecc50288090b76d74a6cc0d295b1188ad18a55a0e1f"),
    // faucet_get_total_fungible_asset_issuance
    word!("0xd70452ecadad601651c2605c0a3c24ec93e48878a91036ff1d651fd68d9e5f9b"),
    // faucet_is_non_fungible_asset_issued
    word!("0x153595fdfbaac21a6172973982e4949e0e73726f49bbd15e20147c0ad87a6af7"),
    // input_note_get_metadata
    word!("0x447b342e38855a9402cde0ea52ecb5e4c1fe542b535a5364cb5caa8e94c82442"),
    // input_note_get_assets_info
    word!("0xe0817bed99fb61180e705b2c9e5ca8c8f0c62864953247a56acbc65b7d58c2d5"),
    // input_note_get_script_root
    word!("0x527036257e58c3a84cf0aa170fb3f219a4553db17d269279355ad164a2b90ac5"),
    // input_note_get_inputs_info
    word!("0xb7f45ec34f7708355551dcf1f82c9c40e2c19252f8d5c98dcf9ef1aa0a3eb878"),
    // input_note_get_serial_number
    word!("0x25815e02b7976d8e5c297dde60d372cc142c81f702f424ac0920190528c547ee"),
    // input_note_get_recipient
    word!("0xd3c255177f9243bb1a523a87615bbe76dd5a3605fcae87eb9d3a626d4ecce33c"),
    // output_note_create
    word!("0xf6d7790691427c5d54ac9dd3b7ed1bb587fa6e864bdf7ba372f022a45c7caa47"),
    // output_note_get_metadata
    word!("0x3db8427f20eb70603b72aa574a986506eb7216312004aeaf8b2a7e55d0049a48"),
    // output_note_get_assets_info
    word!("0xbbf90ac2a7e16ee6d2336f7389d5b972bf0c1fa9938405945b85f948bf24fc4f"),
    // output_note_get_recipient
    word!("0x1ce137f0c5be72832970e6c818968a789f65b97db34515bfebb767705f28db67"),
    // output_note_add_asset
    word!("0xaf22383e4390f4f15a429768f79aa445f8a535bb21b0807172b9ef2de063d9d1"),
    // output_note_set_attachment
    word!("0x800ab6457b20be22a721d61770ab493334004d2b5d01a6bbd245e49554c31a2c"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_output_notes
    word!("0x2511fca9c078cd96e526fd488d1362cbfd597eb3db8452aedb00beffee9782b4"),
    // tx_get_output_notes_commitment
    word!("0x8b9b29c837b5d0834f550d7f32703b35e2ff014b523dd581a09a0b94a925fcec"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_start_foreign_context
    word!("0xcd452e4da22b7ba23ffe5af58d746b137c1e32ae549c222778cac73b38c30647"),
    // tx_end_foreign_context
    word!("0xaa0018aa8da890b73511879487f65553753fb7df22de380dd84c11e6f77eec6f"),
    // tx_get_expiration_delta
    word!("0xa60286e820a755128b2269db5057b0e2d9b79fef6f813bf3fe3337553a8fbb53"),
    // tx_update_expiration_block_delta
    word!("0xa16440a9a8cd2a6d0ff7f5c3bcce2958976e5d3e6e8a6935ff40ae1863c324f0"),
];
