// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 52] = [
    // account_get_initial_commitment
    word!("0x0a0cb376021c606c618d248b00d0f545dbf02968110581d3dba88ecd75b27476"),
    // account_compute_commitment
    word!("0xbd0a999fa0d7459f66a3bb55729ada356a5960bb09455c5267783b95106f54fd"),
    // account_get_id
    word!("0x2fe44dda4696de30933a570b0e38185cf7f534919bc5023a613964e1883c9ba5"),
    // account_get_nonce
    word!("0xbef896156a1ab68fcd12f66acff8efd0c2dafaad4d723e6b76a791d332a4c3f8"),
    // account_incr_nonce
    word!("0xb2ddfd8ffdb960c864d5ee0af739282a9777b38ac55d309ad06a8c9dd614a044"),
    // account_get_code_commitment
    word!("0xd4676cefc2bec981894f73507a75525ba4a49bf04112079e55465de3c0fdd2f3"),
    // account_get_initial_storage_commitment
    word!("0xb20cce8817acaee05270eb43ad3e8808240d09151a83118ea9f63323dd4bc5a9"),
    // account_compute_storage_commitment
    word!("0xa749af2236a87251fcd268c4e82d49890a46058ebec8bbaf51baed16b5279d25"),
    // account_get_item
    word!("0x1af4529f6f63186222059ef41991bbd63702a296b06e6090610dec95c0afa306"),
    // account_get_initial_item
    word!("0x0917b1f34a4461650a5883a4c2a780883bb2ca3ad51810c4076b1672a8e7e0d8"),
    // account_set_item
    word!("0xc7dc4a867084ffccf7e0c109e2189ceba604bec4fc2ca33a42ee310373ad786c"),
    // account_get_map_item
    word!("0x7e22373c844761518ca9dd156e8edb3018f099e7a2afbc4d571b23344b3cb361"),
    // account_get_initial_map_item
    word!("0xfa94427781ff22c4d8a362195b6daa0217a30a9722b47c42c671408c49e010f4"),
    // account_set_map_item
    word!("0x119e11e6a9de4016393d455798f31821f680f56e52a84150c1d010f0b1ac2855"),
    // account_get_initial_vault_root
    word!("0x894c494ea1fcf10a58075c60490607c54f66ec4af6f77c1320c3e6ed2a11cb40"),
    // account_get_vault_root
    word!("0x1e3d8f19d76a87777ca8e07774b5e99c7fd20e51ff834a9f531ca0bde82ed269"),
    // account_add_asset
    word!("0xcdac1e541f6a36ee2911d95fafd1d768992ad10c6685d2b2e4e8ffc008e248aa"),
    // account_remove_asset
    word!("0x5cb52110286c44788cd0d2cdefab4d37a1f086d4cc37d5a524da29a96bf01b81"),
    // account_get_balance
    word!("0xb8ccac74a4a4b108d15235ec6189d58fe4ed1afca392da19a596858480435869"),
    // account_get_initial_balance
    word!("0x2995d6133c7f9ff5263c0dcbc6553d50b2caa79f92982ab0fbda1e963f8269fc"),
    // account_has_non_fungible_asset
    word!("0x3781397f32da1b58b79757828ccfc3f5e02d4a9e314dcdea85d2648eaca51a21"),
    // account_compute_delta_commitment
    word!("0xe52bae69fd1ac0b8dff58dd223961fb28a8159a9b9e2bfb09584a98514964f15"),
    // account_get_num_procedures
    word!("0xf633ec7d9776c462ada535bf44fea0602f16d0a6bb6ca58265f0c4867e2647b6"),
    // account_get_procedure_root
    word!("0x693054519dd35a4106094fb6d5ee1e5f0a6b5b61a9c9c3f3089076093215d9ce"),
    // account_was_procedure_called
    word!("0x701f535bbf646f8e59dd0b05dad2ba5228265f267481f6103ce5addeece28cb7"),
    // account_has_procedure
    word!("0xfb2687afc69061527c6583c52597949e99a28e1444dde349ce8f6cb00be2062e"),
    // faucet_mint_asset
    word!("0x1b0bf4ddc860baac540c71259822307bd1953ff6334839481baa9b3a6eceaf20"),
    // faucet_burn_asset
    word!("0xc62a881559e548b5e6a4e04f9b5b08a17bb71872a92f2eee528f79c3e594a2a6"),
    // faucet_get_total_fungible_asset_issuance
    word!("0xd7495b61190eaeef12188c5ccfdc9d500391d5522a5f9e0a4abd202f5f49320f"),
    // faucet_is_non_fungible_asset_issued
    word!("0xd59e9f9a5314ff8d606079201c2fb7c3f4f0104b4cf8d4056e6f8d876ebca3d9"),
    // input_note_get_metadata
    word!("0x00054c4b097adae656b7d7a7721425d91a1923164bf16b1cab83c730807944e1"),
    // input_note_get_assets_info
    word!("0xa94da7f1c6722aa52db958e026afb58d7850e9c208c18aab3922335985160bba"),
    // input_note_get_script_root
    word!("0x6a21328aff9dcfc3d671eca4fd12e991f4f6046447c2cda0fcf640f94b2e4d28"),
    // input_note_get_inputs_info
    word!("0xe7c25deb5c505b34c7e40bd31d284a01a842250c87b787807f7c49d5bbd10e0e"),
    // input_note_get_serial_number
    word!("0xf3caf62d39561978c7c486680afe80a60abe0285d815de1bf9392a97c6c5312a"),
    // input_note_get_recipient
    word!("0xcb486b16e78907161dda464e7f8ab4ce05d55b78d2f1d0af7dba32b20b842cc0"),
    // output_note_create
    word!("0x0e9c95d4609697a1cd3030e4a971e504a422d4b667728eb2443692f75ac8d760"),
    // output_note_get_metadata
    word!("0x3536347c35d038e03ae573a13fe44ef800452617f3ff905a0be32161f35092b0"),
    // output_note_get_assets_info
    word!("0x62c4e2ae2b7f8ade59fa0b76e53f65f069145fdbe0e02eface1ec16d85a44cd3"),
    // output_note_get_recipient
    word!("0x27240d1c0a13262f6439be45b0d2463e24b49787206cc2164348e971416bf74a"),
    // output_note_add_asset
    word!("0x4d59b0b29b3aa1e70c860fd8281090c3d251cf8778e6797cc4dff09237aa030c"),
    // tx_get_num_input_notes
    word!("0x93fd1eb66b1a58ed838fccaa50dc30959db29374147c7098d71f3dca0f738658"),
    // tx_get_input_notes_commitment
    word!("0x058053d92217a737890ac97d998566eabe8e4c6010c4841968b07959a7df3fa2"),
    // tx_get_num_output_notes
    word!("0xfd1ec808e4ebd96cb1d9e16995c97c484277b6dfb88e327d1033e89d2efb5b10"),
    // tx_get_output_notes_commitment
    word!("0x4746cb16d4bd986468116df3737b4217be0fd900917e1221fb64d6faa7662137"),
    // tx_get_block_commitment
    word!("0x5dd1af16a7175966a53ebba2550351be66d79bc2d3b70cb1af1522f128dbcf23"),
    // tx_get_block_number
    word!("0xde7cfd5058cae688bb6416ee3bea18f7d2296f6077bd9e88aab67ec0d170eaf8"),
    // tx_get_block_timestamp
    word!("0xa04c1588d66348e0bf98003479b61da556714ffa0c70344b0d89a68aa16fb613"),
    // tx_start_foreign_context
    word!("0xef4c2dc04afc2dea945f5561d15679d12450cc7db69e33391e8f9ab6aaedbc95"),
    // tx_end_foreign_context
    word!("0x23dc130183c87f7537c56aad50533cbcb16fbca5d71a17d7655572dfa1b1baab"),
    // tx_get_expiration_delta
    word!("0xbffe80441afba3fea6441d094d87012da55c5dacd5d280db749b74f5e8a10cf8"),
    // tx_update_expiration_block_delta
    word!("0xd681ec53d6a3df1dc1702ab9dd46bcea3830d6f590b9385ccc88583e87ab15fd"),
];
