[package]
name              = "miden-standards-access-ownable2step"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::access::ownable2step"
path      = "ownable2step.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true

[package.metadata.account-component]
description = "Two-step ownership management component"
name        = "miden::standards::access::ownable2step"
version     = "1.0.0"

[[package.metadata.account-component.storage.slots]]
description = "Ownership data (owner and nominated owner)"
name        = "miden::standards::access::ownable2step::owner_config"

[[package.metadata.account-component.storage.slots.type]]
name = "owner_suffix"

[[package.metadata.account-component.storage.slots.type]]
name = "owner_prefix"

[[package.metadata.account-component.storage.slots.type]]
name = "nominated_suffix"

[[package.metadata.account-component.storage.slots.type]]
name = "nominated_prefix"
