[package]
name              = "miden-standards-oracle-price-feed"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::oracle::price_feed"
path      = "price_feed.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
