[package]
name              = "miden-standards-auth-no-auth"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::auth::no_auth"
path      = "no_auth.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true

[package.metadata.account-component]
description = "No authentication component"
name        = "miden::standards::auth::no_auth"
version     = "1.0.0"
