[package]
name    = "miden-standards"
version = "0.18.0"

[lib]
namespace = "miden::standards"
path      = "mod.masm"

[dependencies]
miden-core     = { linkage = "dynamic", version = "0.35" }
miden-protocol = { linkage = "dynamic", version = "0.18.0" }
