syntax = "proto3";
package blockchain;

import "account.proto";
import "block_number.proto";
import "primitives.proto";
import "transaction.proto";

message FeeParameters {
  account.AccountId native_asset_id = 1;
  fixed32 verification_base_fee = 2;
}

message BlockHeader {
  uint32 version = 1;
  primitives.Word prev_block_commitment = 2;
  blockchain.BlockNumber block_num = 3;
  primitives.Word chain_commitment = 4;
  primitives.Word account_root = 5;
  primitives.Word nullifier_root = 6;
  primitives.Word note_root = 7;
  primitives.Word tx_commitment = 8;
  repeated primitives.PublicKey validator_keys = 9;
  primitives.Word tx_kernel_commitment = 10;
  FeeParameters fee_parameters = 11;
  fixed32 timestamp = 12;
}

message BlockAccountUpdate {
  account.AccountId account_id = 1;
  primitives.Word final_state_commitment = 2;
  account.AccountUpdateDetails details = 3;
}

message IndexedOutputNote {
  uint32 note_index_in_batch = 1;
  transaction.OutputNote note = 2;
}

message OutputNoteBatch {
  repeated IndexedOutputNote notes = 1;
}

message BlockBody {
  repeated BlockAccountUpdate updated_accounts = 1;
  repeated OutputNoteBatch output_note_batches = 2;
  repeated primitives.Word created_nullifiers = 3;
  repeated transaction.TransactionHeader transactions = 4;
}

message BlockProof {}

message SignedBlock {
  BlockHeader header = 1;
  BlockBody body = 2;
  repeated primitives.Signature signatures = 3;
}
