syntax = "proto3";
package transaction;

import "account.proto";
import "note.proto";
import "primitives.proto";

message TransactionId {
  primitives.Digest id = 1;
}

message InputNoteCommitment {
  primitives.Digest nullifier = 1;
  optional note.NoteHeader header = 2;
}

message TransactionHeader {
  TransactionId transaction_id = 1;
  account.AccountId account_id = 2;
  primitives.Digest initial_state_commitment = 3;
  primitives.Digest final_state_commitment = 4;
  repeated InputNoteCommitment input_notes = 5;
  repeated note.NoteHeader output_notes = 6;
}

message PublicOutputNote {
  note.NoteMetadata metadata = 1;
  note.NoteDetails details = 2;
  note.NoteAttachments attachments = 3;
}

message PrivateOutputNote {
  note.NoteHeader header = 1;
  note.NoteAttachments attachments = 2;
}

message OutputNote {
  oneof note {
    PublicOutputNote public = 1;
    PrivateOutputNote private = 2;
  }
}

message TxAccountUpdate {
  account.AccountId account_id = 1;
  primitives.Word initial_state_commitment = 2;
  primitives.Word final_state_commitment = 3;
  primitives.Word account_patch_commitment = 4;
  account.AccountUpdateDetails details = 5;
}

message ProvenTransactionData {
  TxAccountUpdate account_update = 1;
  repeated InputNoteCommitment input_notes = 2;
  repeated OutputNote output_notes = 3;
  fixed32 reference_block_num = 4;
  primitives.Word reference_block_commitment = 5;
  fixed32 expiration_block_num = 6;
  // Canonically serialized ExecutionProof.
  bytes proof = 7;
}
