[package]
name              = "miden-standards-oracle-price-reader-manager"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::oracle::price_reader_manager"
path      = "price_reader_manager.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
