[package]
name              = "miden-standards-note-note-creator"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::note::note_creator"
path      = "note_creator.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true

[package.metadata.account-component]
description = "Exposes the `create_note` procedure for creating output notes"
name        = "miden::standards::note::note_creator"
version     = "1.0.0"
