[package]
name              = "miden-standards-fees-policies-constant-fee"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::fees::policies::constant_fee"
path      = "constant_fee.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
