[package]
name              = "miden-agglayer-claim"
version.workspace = true

[lib]
namespace = "agglayer::note_scripts::claim"
path      = "claim.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
miden-agglayer.workspace  = true
