// This file is @generated by `make update-note-costs`. Do not edit by hand.
// Values are maxima across the benchmarked paths; see `miden_standards::note::costs` for the
// caveats on what they do and do not cover.

/// Cycles of consuming a CLAIM note: L1 origin 53761, L2 origin 63923 (maximum).
pub const CLAIM_CONSUMPTION_CYCLES: u32 = 63923;

/// Cycles of consuming a B2AGG note: empty frontier 153889 (maximum), 2^31-1 leaves 88605.
pub const B2AGG_CONSUMPTION_CYCLES: u32 = 153889;

/// Cycles of consuming a CONFIG_AGG_BRIDGE note (single benchmarked path).
pub const CONFIG_AGG_BRIDGE_CONSUMPTION_CYCLES: u32 = 34465;

/// Cycles of consuming a DEREGISTER_AGG_FAUCET note (single benchmarked path).
pub const DEREGISTER_AGG_FAUCET_CONSUMPTION_CYCLES: u32 = 33763;

/// Cycles of consuming an UPDATE_GER note (single benchmarked path).
pub const UPDATE_GER_CONSUMPTION_CYCLES: u32 = 24439;

/// Cycles of consuming a REMOVE_GER note (single benchmarked path).
pub const REMOVE_GER_CONSUMPTION_CYCLES: u32 = 25598;
