// This file is @generated by `make update-note-costs`. Do not edit by hand.
// Values are maxima across the benchmarked paths; see `miden_standards::note::costs` for the
// caveats on what they do and do not cover.

/// Cycles of consuming a CLAIM note: L1 origin 54377, L2 origin 67358 (maximum).
pub const CLAIM_CONSUMPTION_CYCLES: u32 = 67358;

/// Cycles of consuming a B2AGG note: empty frontier 151598 (maximum), 2^31-1 leaves 86996.
pub const B2AGG_CONSUMPTION_CYCLES: u32 = 151598;

/// Cycles of consuming a CONFIG_AGG_BRIDGE note (single benchmarked path).
pub const CONFIG_AGG_BRIDGE_CONSUMPTION_CYCLES: u32 = 31452;

/// Cycles of consuming a DEREGISTER_AGG_FAUCET note (single benchmarked path).
pub const DEREGISTER_AGG_FAUCET_CONSUMPTION_CYCLES: u32 = 31467;

/// Cycles of consuming an UPDATE_GER note (single benchmarked path).
pub const UPDATE_GER_CONSUMPTION_CYCLES: u32 = 22324;

/// Cycles of consuming a REMOVE_GER note (single benchmarked path).
pub const REMOVE_GER_CONSUMPTION_CYCLES: u32 = 24177;
