[package]
name              = "miden-standards-wallets-basic-wallet"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::wallets::basic_wallet"
path      = "basic_wallet.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true

[package.metadata.account-component]
description = "Basic wallet component for receiving and sending assets"
name        = "miden::standards::wallets::basic_wallet"
version     = "1.0.0"
