[workspace]
members = ["bridge"]

[workspace.package]
version = "0.17.0"

[workspace.dependencies]
miden-agglayer  = { linkage = "dynamic", version = "0.17.0" }
miden-core      = { linkage = "dynamic", version = "0.33" }
miden-protocol  = { linkage = "dynamic", version = "0.17.0" }
miden-standards = { linkage = "dynamic", version = "0.17.0" }
