[workspace]
members = ["bridge"]

[workspace.package]
version = "0.16.0"

[workspace.dependencies]
miden-agglayer  = { linkage = "static", version = "0.16.0" }
miden-core      = { linkage = "dynamic", version = "0.32" }
miden-protocol  = { linkage = "dynamic", version = "0.16.0" }
miden-standards = { linkage = "dynamic", version = "0.16.0" }
