[workspace]
members = ["kernels/batch", "kernels/transaction", "protocol", "utils"]

[workspace.package]
version = "0.16.0"

[workspace.dependencies]
miden-core           = { linkage = "dynamic", path = "miden-core.masp" }
miden-protocol-utils = { linkage = "static", path = "utils" }
miden-tx-kernel      = { linkage = "dynamic", path = "kernels/transaction" }
