[package]
name    = "miden-standards-faucets-fungible-faucet"
version = "0.16.0"

[lib]
kind      = "account-component"
namespace = "miden::standards::components::faucets::fungible_faucet"
path      = "fungible_faucet.masm"

[dependencies]
miden-core      = { linkage = "dynamic", version = "0.23.4" }
miden-protocol  = { linkage = "dynamic", version = "0.16.0" }
miden-standards = { linkage = "static", version = "0.16.0" }
