[package]
name              = "miden-standards-pass-through"
version.workspace = true

[lib]
kind      = "account-component"
namespace = "miden::standards::components::pass_through"
path      = "pass_through.masm"

[dependencies]
miden-core.workspace      = true
miden-protocol.workspace  = true
miden-standards.workspace = true
